### ISSUE TITLE
Upload DUPLICATE NAMES

### ISSUE THREAD

**Issue by yurinb** [yurinb/Mussum_2.0-API#2]
Resolver o que fazer quando receber upload de arquivo com o mesmo nome/diretório

(Atualmente não está fazendo upload, esta criando uma entidade repetida no banco de dados também)

**Comment by matheusviegas** [comment]
I suggest to concatenate on the end of the file name the parenthesis (1), (2), (N..) just like the web browsers do when we want to download a file that already exists on the destination folder and let the user manipulate it whenever he wants to.

Once the upload completed, mark the duplicate file as draft and then let the user decide if puts it visible or not.
